theme: День открытых дверей
Актив фитнес студия Адрес: 141077 г. Королев, Октябрьский бульвар, дом 5.
<a href="https://activf2017.blogspot.ru/"><img alt="Актив студия фитнеса Королёв" src="https://goo.gl/gjB9GV" height="31" width="88" border="0" /></a>
